version: "3.8"
services:
  mysql-container:
    container_name: mysql-container
    image: mysql:8.0.22
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "sample"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    networks:
      - default
    volumes:
      - ./docker/volumes/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/volumes/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
